# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

lodestar-besu-001:
  global:
    main:
      network: bal-devnet-1
      engineEndpoint: http://besu-lodestar-001:8551
      rpcEndpoint: http://besu-lodestar-001:8545
      beaconEndpoint: http://lodestar-besu-001:5052
    checkpointSync:
      enabled: false
      addresses:
        bal-devnet-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.bal-devnets.node_ingress.combined}>@bn-hc-bootnode-1.bal-devnet-1.ethpandaops.io
    clientArgs:
      networks:
        bal-devnet-1:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
              - --bootnodes=enode://b6ea0654360d2f380c3a138e7a0b2a773bdac6c7f591e34ca2ed0c092cbe9a1eb5b49662c75c45bb43047db6eef8c34d02805c3562106c8c8722cdf48ee9c1a8@167.235.68.172:30303
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Pruning.Mode=None
              - --config=none
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Seq.ServerUrl=https://seq.nethermind.io
              - --Seq.ApiKey=yuOqjKOHhZCw2D2U7pmL
              - --Metrics.PushGatewayUrl=http://94.237.52.161:9000/metrics/nethermind-iudiy4raagaizaih1phuaShekighoJ2ixaecahvii7ohte3oozeeh0eTh7Aich1Shee9ceetuy3iGhexoh5naithoot8rebi7fee
              - --Discovery.Bootnodes=enode://b6ea0654360d2f380c3a138e7a0b2a773bdac6c7f591e34ca2ed0c092cbe9a1eb5b49662c75c45bb43047db6eef8c34d02805c3562106c8c8722cdf48ee9c1a8@167.235.68.172:30303
            geth:
              - --http.api=eth,net,web3,debug,admin,txpool,trace
              - --http.vhosts=*
              - --networkid=7029915638
              - --syncmode=full
              - --history.state=0
              - --gcmode=archive
              - --syncmode=full
              - --bootnodes=enode://b6ea0654360d2f380c3a138e7a0b2a773bdac6c7f591e34ca2ed0c092cbe9a1eb5b49662c75c45bb43047db6eef8c34d02805c3562106c8c8722cdf48ee9c1a8@167.235.68.172:30303,enode://e452c1d148d86f48c38acd7561e3a3518e41b8141a604d2a332e9350ed4bea3c685c9dbd4c3fac242906479ad9eb2373cb7501a9c37637d9e42262d1f6128910@91.98.138.241:30303
              - --rpc.allow-unprotected-txs
            erigon:
              - --chain=dev
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --prune=htc
              - --networkid=7029915638
              - --db.size.limit=500GB
              - --bootnodes=enode://d5c0bd49166a920cc6bf408b39adcd4b88778eef21199bd9543f63cefd60f84680ae56afb3df81a2336f6c1b52e8e3961d0f72fdb4a5f378dbb2e5d5f24794bf@91.98.138.241:9010,enode://e452c1d148d86f48c38acd7561e3a3518e41b8141a604d2a332e9350ed4bea3c685c9dbd4c3fac242906479ad9eb2373cb7501a9c37637d9e42262d1f6128910@91.98.138.241:30303?discport=30303
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-PC4QCpP9uKlV6B2yQAn29AyY5fntyF0xxHKftrmUvheidyuWbr8ljhaA1RiBovMO9TlJ59YlJnvMrWnAi_Momh0iVkSh2F0dG5ldHOIADAAAAAAAACDY2djgYCEZXRoMpCopcJfgCVVkP__________gmlkgnY0gmlwhKfrRKyDaXA2kCoBBPgcGt6LAAAAAAAAAAGDbmZkhAAAAACJc2VjcDI1NmsxoQIKMkYU0aS8uxBYryDr98OUdLChI8WCBFO9mWLKcH9Bk4hzeW5jbmV0cw-DdGNwgiMohHRjcDaCIyqDdWRwgiMohHVkcDaCIyo,enr:-PC4QGQ8SfUObY9phUZQBMn4B0JxzEZsy6cErdBjBpZul5rjOvXn3p__YyyNy3soVH_yumd3sr70rQUrIrW-MG-JB0USh2F0dG5ldHOIDAAAAAAAAACDY2djgYCEZXRoMpCopcJfgCVVkP__________gmlkgnY0gmlwhHTL4IaDaXA2kCoBBPgcGjAwAAAAAAAAAAGDbmZkhAAAAACJc2VjcDI1NmsxoQK7dJgHcZtwC1D5-mZV0G89uFQWmpykiCv77On2F0sY-IhzeW5jbmV0cw-DdGNwgiMohHRjcDaCIyqDdWRwgiMohHVkcDaCIyo
              - --persistNetworkIdentity
              - --rest.namespace="*"
              - --nat=true
              - --disablePeerScoring
              - --serveHistoricalState
              - --checkpointSyncUrl=https://checkpoint-sync.bal-devnet-1.ethpandaops.io/
              - --forceCheckpointSync
              - --network.connectToDiscv5Bootnodes
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-LG4QO5ezbzcEfHnxLSUwCZuLbN6sY7xp3VCTirRZRIoPK_hZmuHp8ziS6lO8ERk-GeJEu-0vQeJgKfoQIuliznvTicDg2V0aMvKhJ1SoMeEaUQq7oRldGgykKilwl________________-CaWSCdjSCaXCEW2KK8YlzZWNwMjU2azGhA9XAvUkWapIMxr9AizmtzUuId47vIRmb2VQ_Y879YPhGg3RjcIIjMoN1ZHCCIzI,enr:-Pm4QOYEe9_wz-CqsVBWk_DvwddeZlsfLMqMoqCVk7RSycClE_qUor-tMvf5QoG57hc9Q5ifqD49Yv6dpdz7zU9S-9iBl4dhdHRuZXRziAAAAAAAwAAAg2NnY4GAhGV0aDKQqKXCX4AlVZD__________4JpZIJ2NIJpcIRbYorxg2lwNpAqAQT4HB7TTAAAAAAAAAABg25mZIQAAAAAiXNlY3AyNTZrMaED3b_9xNMXdFxy4j6gKGMxDtPWoj-bZole6Fg2JLnAN3-Ic3luY25ldHOIAAAAAAAAAACDdGNwgiMohHRjcDaCIyqDdWRwgiMohHVkcDaCIyo
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-LG4QO5ezbzcEfHnxLSUwCZuLbN6sY7xp3VCTirRZRIoPK_hZmuHp8ziS6lO8ERk-GeJEu-0vQeJgKfoQIuliznvTicDg2V0aMvKhJ1SoMeEaUQq7oRldGgykKilwl________________-CaWSCdjSCaXCEW2KK8YlzZWNwMjU2azGhA9XAvUkWapIMxr9AizmtzUuId47vIRmb2VQ_Y879YPhGg3RjcIIjMoN1ZHCCIzI
              - --bootstrap-node=enr:-Pm4QOYEe9_wz-CqsVBWk_DvwddeZlsfLMqMoqCVk7RSycClE_qUor-tMvf5QoG57hc9Q5ifqD49Yv6dpdz7zU9S-9iBl4dhdHRuZXRziAAAAAAAwAAAg2NnY4GAhGV0aDKQqKXCX4AlVZD__________4JpZIJ2NIJpcIRbYorxg2lwNpAqAQT4HB7TTAAAAAAAAAABg25mZIQAAAAAiXNlY3AyNTZrMaED3b_9xNMXdFxy4j6gKGMxDtPWoj-bZole6Fg2JLnAN3-Ic3luY25ldHOIAAAAAAAAAACDdGNwgiMohHRjcDaCIyqDdWRwgiMohHVkcDaCIyo
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-LG4QO5ezbzcEfHnxLSUwCZuLbN6sY7xp3VCTirRZRIoPK_hZmuHp8ziS6lO8ERk-GeJEu-0vQeJgKfoQIuliznvTicDg2V0aMvKhJ1SoMeEaUQq7oRldGgykKilwl________________-CaWSCdjSCaXCEW2KK8YlzZWNwMjU2azGhA9XAvUkWapIMxr9AizmtzUuId47vIRmb2VQ_Y879YPhGg3RjcIIjMoN1ZHCCIzI,enr:-Pm4QOYEe9_wz-CqsVBWk_DvwddeZlsfLMqMoqCVk7RSycClE_qUor-tMvf5QoG57hc9Q5ifqD49Yv6dpdz7zU9S-9iBl4dhdHRuZXRziAAAAAAAwAAAg2NnY4GAhGV0aDKQqKXCX4AlVZD__________4JpZIJ2NIJpcIRbYorxg2lwNpAqAQT4HB7TTAAAAAAAAAABg25mZIQAAAAAiXNlY3AyNTZrMaED3b_9xNMXdFxy4j6gKGMxDtPWoj-bZole6Fg2JLnAN3-Ic3luY25ldHOIAAAAAAAAAACDdGNwgiMohHRjcDaCIyqDdWRwgiMohHVkcDaCIyo
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=INFO
              - --light-client-data-serve=false
              - --bootstrap-node=enr:-LG4QO5ezbzcEfHnxLSUwCZuLbN6sY7xp3VCTirRZRIoPK_hZmuHp8ziS6lO8ERk-GeJEu-0vQeJgKfoQIuliznvTicDg2V0aMvKhJ1SoMeEaUQq7oRldGgykKilwl________________-CaWSCdjSCaXCEW2KK8YlzZWNwMjU2azGhA9XAvUkWapIMxr9AizmtzUuId47vIRmb2VQ_Y879YPhGg3RjcIIjMoN1ZHCCIzI
              - --bootstrap-node=enr:-Pm4QOYEe9_wz-CqsVBWk_DvwddeZlsfLMqMoqCVk7RSycClE_qUor-tMvf5QoG57hc9Q5ifqD49Yv6dpdz7zU9S-9iBl4dhdHRuZXRziAAAAAAAwAAAg2NnY4GAhGV0aDKQqKXCX4AlVZD__________4JpZIJ2NIJpcIRbYorxg2lwNpAqAQT4HB7TTAAAAAAAAAABg25mZIQAAAAAiXNlY3AyNTZrMaED3b_9xNMXdFxy4j6gKGMxDtPWoj-bZole6Fg2JLnAN3-Ic3luY25ldHOIAAAAAAAAAACDdGNwgiMohHRjcDaCIyqDdWRwgiMohHVkcDaCIyo

  besu:
    enabled: true
    fullnameOverride: besu-lodestar-001
    image:
      repository: ethpandaops/besu
      tag: bal-devnet-1
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31151
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: bal-devnet-1
      testnet: bal-devnet-1
      ethereum_network: bal-devnet-1
      ethereum_role: execution
      consensus_client: lodestar
      execution_client: besu
      ethereum_instance: besu-lodestar-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.bal-devnet-1.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.bal-devnet-1.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.bal-devnet-1.ethpandaops.io/el/besu.json;
            ENODES_URI=https://config.bal-devnet-1.ethpandaops.io/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"

  lodestar:
    checkpointSync:
      enabled: false
      addresses:
        bal-devnet-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.bal-devnets.node_ingress.combined}>@bn-hc-bootnode-1.bal-devnet-1.ethpandaops.io
    enabled: true
    fullnameOverride: lodestar-besu-001
    image:
      repository: ethpandaops/lodestar
      tag: bal-devnet-1
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32151
    podLabels:
      network: bal-devnet-1
      testnet: bal-devnet-1
      ethereum_network: bal-devnet-1
      ethereum_role: consensus
      consensus_client: lodestar
      execution_client: besu
      ethereum_instance: lodestar-besu-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
      - name: init-genesis
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            apk add jq curl sed;
            DEPOSIT_CONTRACT_URI=https://config.bal-devnet-1.ethpandaops.io/cl/deposit_contract.txt;
            DEPOSIT_CONTRACT_BLOCK_URI=https://config.bal-devnet-1.ethpandaops.io/cl/deposit_contract_block.txt;
            DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.bal-devnet-1.ethpandaops.io/cl/deposit_contract_block_hash.txt;
            GENESIS_CONFIG_URI=https://config.bal-devnet-1.ethpandaops.io/cl/config.yaml;
            GENESIS_SSZ_URI=https://config.bal-devnet-1.ethpandaops.io/cl/genesis.ssz;
            mkdir -p /data/network-config;
            curl -s https://config.bal-devnet-1.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
            if ! [ -f /data/network-config/genesis.ssz ];
            then
              wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
              wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
              wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
              wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
              wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
              echo "genesis init done";
            else
              echo "genesis exists. skipping...";
            fi;
            (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
            mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
            echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
