# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/checkpointz.yaml.j2

checkpointz:
  fullnameOverride: checkpointz
  replicas: 1

  image:
    repository: ethpandaops/checkpointz
    tag: gloas-debian-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 64m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: checkpoint-sync.bal-devnet-1.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

    tls:
      - hosts:
          - checkpoint-sync.bal-devnet-1.ethpandaops.io
        secretName: bal-devnet-1-checkpoint-sync-tls

  config:
    global:
      listenAddr: ":5555"
      logging: "info" # panic,fatal,warm,info,debug,trace
      metricsAddr: ":9090"

    checkpointz:
      mode: full
      caches:
        blocks:
          max_items: 100
        states:
          max_items: 5
      historical_epoch_count: 20

    beacon:
      upstreams:
        - name: rpc-lodestar-geth-001
          address: http://lodestar-geth-001:5052
          dataProvider: false
        - name: hc-lodestar-besu-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.bal-devnets.node_ingress.combined}>@bn-hc-lodestar-besu-super-1.srv.bal-devnet-1.ethpandaops.io
          dataProvider: true
        - name: hc-lodestar-geth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.bal-devnets.node_ingress.combined}>@bn-hc-lodestar-geth-super-1.srv.bal-devnet-1.ethpandaops.io
          dataProvider: false
        - name: hc-lodestar-nethermind-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.bal-devnets.node_ingress.combined}>@bn-hc-lodestar-nethermind-super-1.srv.bal-devnet-1.ethpandaops.io
          dataProvider: false
        - name: hc-lodestar-nimbusel-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.bal-devnets.node_ingress.combined}>@bn-hc-lodestar-nimbusel-super-1.srv.bal-devnet-1.ethpandaops.io
          dataProvider: true
        - name: hc-lodestar-reth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.bal-devnets.node_ingress.combined}>@bn-hc-lodestar-reth-super-1.srv.bal-devnet-1.ethpandaops.io
          dataProvider: false
