# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: ethpandaops/dora
    tag: eip7928-support-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 3Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="//raw.githubusercontent.com/pk910/panda-menu/refs/heads/main/inject.js"></script></head>';
        sub_filter_once off;
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - host: dora.bal-devnet-1.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  name: bal-devnet-1
  configPath: "https://config.bal-devnet-1.ethpandaops.io/cl/config.yaml"
  validatorNamesInventory: "https://config.bal-devnet-1.ethpandaops.io/api/v1/nodes/validator-ranges"
  ethExplorerLink: "https://explorer.bal-devnet-1.ethpandaops.io"
  publicRpcUrl: "https://rpc.bal-devnet-1.ethpandaops.io"
  rainbowkitProjectId: "15fe4ab4d5c0bcb6f0dc7c398301ff0e"
  executionGenesisConfig: "https://config.bal-devnet-1.ethpandaops.io/el/genesis.json"
  apiRequireAuth: False
  apiAuthSecret: "<path:/secrets/services/services.enc.yaml#dora | jsonPath {.api_secret}>"
  apiWhitelistedIPs: []
  apiDefaultRateLimit: 60
  apiDisableDefaultRateLimit: false
  proxyCount: 2
  executionIndexerEnabled: True
  executionIndexerRetention: 336h
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"
    - name: FRONTEND_SHOW_SENSITIVE_PEER_INFOS
      value: "true"
    - name: API_CORS_ORIGINS
      value: "*"
    - name: FRONTEND_ENABLE_DAS_GUARDIAN_MASS_SCAN
      value: "true"
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"
    persistence:
      size: "50Gi"

  mevRelays:
    - index: 0
      name: "Flashbots"
      url: "http://mev-relay-1.bal-devnet-1.ethpandaops.io:9062/"

  authGroups:
    pandaops:
      credentials:
        username: ""
        password: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.bal-devnets.node_ingress.combined}>"

  endpointsUrl: "https://raw.githubusercontent.com/ethpandaops/bal-devnets/refs/heads/master/kubernetes/devnet-1/dora/endpoints-cl.yaml"
  executionEndpointsUrl: "https://raw.githubusercontent.com/ethpandaops/bal-devnets/refs/heads/master/kubernetes/devnet-1/dora/endpoints-el.yaml"
